source/parkingapp/urls.py
from django.urls import path
from . import views
# from .views import password_change
from django.contrib.auth import views as auth_views

app_name = 'parkingapp'
urlpatterns = [
    path('', views.sign_in, name='sign-in'),
    path('index', views.index, name='index'),
    path('sign-up', views.sign_up, name="sign-up"),
    path('sign-out', views.sign_out, name="sign-out"),
    path('update-account', views.update_account, name="update-account"),
    path('change-password',views.password_change,name='change-password'),
    path('account-info', views.account_info, name="account-info"),
    path('transfer-funds', views.transfer_funds, name="transfer-funds"),
    path('lot-attendant-home', views.lot_attendant_home, name="lot-attendant-home"),
    path('reserve-spot', views.reserve_spot, name="reserve-spot"),
    path('manage-lot', views.manage_lot, name="manage-lot"),
    path('supervisor-home', views.supervisor_home, name="supervisor-home"),
    path('create-event', views.create_event, name="create-event"),
    path('new-lot', views.new_lot, name="new-lot"),
    path('create-lot', views.create_lot, name="create-lot"),
    path('list-lot/<int:lot_id>/', views.list_lot, name="list-lot"),
    path('make-reservation/<int:lot_data_id>/<int:selected_event_id>/<str:spot_type>/', views.make_reservation, name="make-reservation"),
]

source/projectmain/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='parkingapp:sign-in')),
    path('parkingapp/', include('parkingapp.urls')),
    path('admin/', admin.site.urls),
]

source/parkingapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

# This is how we store data that Django's default User class doesn't have built in.
# We can add more fields to this later if we need to
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    isSupervisor = models.BooleanField(default=False)
    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Event(models.Model):
    supervisor = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name + " " + " " + self.address + " " + self.supervisor.username

class ParkingLot(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    numMotorcycleSpots = models.IntegerField(default=0)
    numCarSpots = models.IntegerField(default=0)
    numOversizeSpots = models.IntegerField(default=0)
    motorcycleSpotPrice = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    carSpotPrice = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    oversizeSpotPrice = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    def __str__(self):
        return self.nickname

class ParkingLotEventData(models.Model):
    parkingLot = models.ForeignKey(ParkingLot, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    distanceFromEvent = models.DecimalField(max_digits=6, decimal_places=1)
    availableMotorcycleSpots = models.IntegerField()
    availableCarSpots = models.IntegerField()
    availableOversizeSpots = models.IntegerField()


# spotType is 1 for motorcycle, 2 for car, 3 for oversize
class ParkingSpot(models.Model):
    parkingLotEventData = models.ForeignKey(ParkingLotEventData, on_delete=models.CASCADE)
    renter = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    spotType = models.CharField(max_length=1)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=1.0)
    confirmationCode = models.CharField(max_length=6)

source/parkingapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,PasswordChangeForm
from django import forms
from django.contrib.auth.models import User

class UserCreationFormExtended(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name')
        # exclude = ('password1','password2')

class UpdatePassword(PasswordChangeForm):
    class Meta:
        model = User
        fields = ('oldpassword','password1','password2')

source/parkingapp/views.py
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import decimal
import random

from .forms import UpdatePassword, UserCreationFormExtended,EditProfileForm

from .models import Event, ParkingLot, ParkingLotEventData, ParkingSpot

from datetime import datetime


# Homepage
@login_required(login_url='parkingapp:sign-in')
def index(request):
    reservation_list = request.user.parkingspot_set.all()
    event_list = Event.objects.order_by('date')

    context = {"reservation_list": reservation_list,
               'event_list': event_list}
    return render(request, "parkingapp/index.html", context)


# Sign-in page
def sign_in(request):
    context = {}
    if request.user.is_authenticated:
        return redirect('parkingapp:index')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('parkingapp:index')
        else:
            messages.info(request, 'Username or password is incorrect')
            return render(request, "parkingapp/sign_in.html", context)

    return render(request, "parkingapp/sign_in.html", context)


# First time sign-up
# @login_required
def sign_up(request):
    if request.user.is_authenticated:
        return redirect('parkingapp:index')

    form = UserCreationFormExtended()

    if request.method == 'POST':
        form = UserCreationFormExtended(request.POST)
        if form.is_valid():
            form.save()
            # user = form.cleaned_data.get('username')
            # messages.success(request, 'Account was created for ' + user)
            return redirect('parkingapp:sign-in')

    context = {'form': form}
    return render(request, "parkingapp/sign_up.html", context)


@login_required(login_url='parkingapp:sign-in')
def sign_out(request):
    logout(request)
    return redirect('parkingapp:sign-in')


# Update account info
@login_required(login_url='parkingapp:sign-in')
def update_account(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('parkingapp:account-info')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'parkingapp/update_account.html',args)

@login_required(login_url='parkingapp:sign-in')
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request,user)
            messages.success(request, 'Your password was successfully changed!')
            return redirect('parkingapp:account-info')
        # else:
        #     messages.error(request, 'Please correct the error below')
    else:
        form=PasswordChangeForm(request.user)
    return render(request, 'parkingapp/change-password.html', {'form':form})
   



@login_required(login_url='parkingapp:sign-in')
def new_lot(request):
    context = {}
    return render(request, "parkingapp/new_lot.html", context)

# Creates a new parking lot, which can then be listed for events.
# Gets called by a form on the manage_lot page
@login_required(login_url='parkingapp:sign-in')
def create_lot(request):
    nickname = request.POST['lot_nickname']
    address = request.POST['lot_address']
    num_motorcycle_spots = request.POST['num-motorcycle-spots']
    num_car_spots = request.POST['num-car-spots']
    num_oversize_spots = request.POST['num-oversize-spots']
    motorcycle_spot_price = request.POST['motorcycle-spot-price']
    car_spot_price = request.POST['car-spot-price']
    oversize_spot_price = request.POST['oversize-spot-price']

    lot = ParkingLot(
        owner=request.user,
        nickname=nickname, 
        address=address,
        numMotorcycleSpots=num_motorcycle_spots,
        numCarSpots=num_car_spots,
        numOversizeSpots=num_oversize_spots,
        motorcycleSpotPrice=motorcycle_spot_price,
        carSpotPrice=car_spot_price,
        oversizeSpotPrice=oversize_spot_price
    )
    lot.save()

    return HttpResponseRedirect(reverse('parkingapp:manage-lot'))


# List an existing lot for an event
# This gets called by a form on the manage_lot page
@login_required(login_url='parkingapp:sign-in')
def list_lot(request, lot_id):
    lot = get_object_or_404(ParkingLot, pk=lot_id)
    event_id = request.POST['selected-event']
    distance_from_event = request.POST['distance-from-event']
    event = get_object_or_404(Event, pk=event_id)
    available_motorcycle_spots = lot.numMotorcycleSpots
    available_car_spots = lot.numCarSpots
    available_oversize_spots = lot.numOversizeSpots

    lot_event_data = ParkingLotEventData(
        parkingLot=lot,
        event=event,
        distanceFromEvent=distance_from_event,
        availableMotorcycleSpots=available_motorcycle_spots,
        availableCarSpots=available_car_spots,
        availableOversizeSpots=available_oversize_spots
    )
    lot_event_data.save()

    # Create the parking spots for this lot and event
    for i in range(available_motorcycle_spots):
        ParkingSpot(parkingLotEventData=lot_event_data, spotType='1', price=lot.motorcycleSpotPrice).save()
    for i in range(available_car_spots):
        ParkingSpot(parkingLotEventData=lot_event_data, spotType='2', price=lot.carSpotPrice).save()
    for i in range(available_oversize_spots):
        ParkingSpot(parkingLotEventData=lot_event_data, spotType='3', price=lot.oversizeSpotPrice).save()

    return HttpResponseRedirect(reverse('parkingapp:manage-lot'))


# View to create new event. Runs within the supervisor homepage
@login_required(login_url='parkingapp:sign-in')
def create_event(request):
    if not request.user.profile.isSupervisor:
        return HttpResponseRedirect(reverse('parkingapp:index'))
        
    event_name = request.POST['event_name']
    event_address = request.POST['event_address']
    event_date = datetime.strptime(request.POST['event_date'], "%Y-%m-%d").date()

    event = Event(supervisor=request.user, name=event_name, address=event_address, date=event_date)
    event.save()

    return HttpResponseRedirect(reverse('parkingapp:supervisor-home'))


# Supervisor overview
@login_required(login_url='parkingapp:sign-in')
def supervisor_home(request):
    if not request.user.profile.isSupervisor:
        return HttpResponseRedirect(reverse('parkingapp:index'))

    event_list = Event.objects.order_by('date')
    context = {'event_list': event_list}
    return render(request, "parkingapp/supervisor_home.html", context)


# Manage lot
@login_required(login_url='parkingapp:sign-in')
def manage_lot(request):
    lot_list = request.user.parkinglot_set.all()
    event_list = Event.objects.order_by('date')
    lot_event_data_list = ParkingLotEventData.objects.filter(parkingLot__in=request.user.parkinglot_set.all())
    context = {'lot_list': lot_list, 'event_list': event_list, 'lot_event_data_list': lot_event_data_list}
    return render(request, "parkingapp/manage_lot.html", context)


# Reserve parking spot
@login_required(login_url='parkingapp:sign-in')
def reserve_spot(request):
    event_list = Event.objects.order_by('date')
    parking_list = []
    spot_type = None
    selected_event_id = None


    if request.method == 'POST':
        selected_event_id = request.POST['selected-event']
        spot_type = request.POST['spot-type']

        event = Event.objects.get(id=selected_event_id)
        if spot_type == "1":
            parking_list = event.parkingloteventdata_set.filter(
                availableMotorcycleSpots__gte=1
            ).order_by(
                '-distanceFromEvent'
            )
        elif spot_type == "2":
            parking_list = event.parkingloteventdata_set.filter(
                availableCarSpots__gte=1
            ).order_by(
                '-distanceFromEvent'
            )
        elif spot_type == "3":
            parking_list = event.parkingloteventdata_set.filter(
                availableOversizeSpots__gte=1
            ).order_by(
                '-distanceFromEvent'
            )

    context = {
        'event_list': event_list,
        'parking_list': parking_list,
        'spot_type': spot_type,
        'selected_event_id': selected_event_id
    }
    return render(request, "parkingapp/reserve_spot.html", context)


@login_required(login_url='parkingapp:sign-in')
def make_reservation(request, lot_data_id, selected_event_id, spot_type):
    lot_data = ParkingLotEventData.objects.get(id=lot_data_id)
    parking_spots = lot_data.parkingspot_set.filter(
            spotType=spot_type
        ).filter(
            renter=None
        )

    if spot_type == "1":
        lot_data.availableMotorcycleSpots = lot_data.availableMotorcycleSpots - 1
    elif spot_type == "2":
        lot_data.availableCarSpots = lot_data.availableCarSpots - 1
    else:
        lot_data.availableOversizeSpots = lot_data.availableOversizeSpots - 1
    lot_data.save()

    parking_spot = parking_spots[0]
    parking_spot.renter = request.user
    parking_spot.confirmationCode = str(random.randrange(100000, 999999))
    parking_spot.save()

    request.user.profile.balance -= parking_spot.price
    request.user.save()
    parking_spot.parkingLotEventData.parkingLot.owner.profile.balance += decimal.Decimal(0.75) * parking_spot.price

source/parkingapp/templates/parkingapp/account_info.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Your Account Info</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <div>
        <nav class="navbar fixed-top navbar-dark bg-primary" role="navigation">
            <h1 class="navbar-brand">BigBlueParkingGenie</h1>
            <div>
                <span> <!-- Directory -->
                    <a href="{% url 'parkingapp:index' %}"><button type="button" class="btn btn-light">Home</button></a>
                    <a href="{% url 'parkingapp:account-info' %}"><button type="button" class="btn btn-light active">Account</button></a>
                    <a href="{% url 'parkingapp:reserve-spot' %}"><button type="button" class="btn btn-light">Find Parking</button></a>
                    <a href="{% url 'parkingapp:manage-lot' %}"><button type="button" class="btn btn-light">List Your Lot</button></a>
                    <a href="{% url 'parkingapp:sign-out'%}"><button type="button" class="btn btn-danger">Log Out</button></a>
                </span>
            </div>
        </nav><br>
        
        <div class="m-5 p-5"> <!-- view specific code here -->
            <div class="container rounded bg-light">
            {% if messages %}
            <div class="rounded bg-success text-center m-3 p-3">
                {% for message in messages %}
                    <p class="text-light font-weight-bold">{{message}}</p>
                {% endfor %}
            </div>
            {% endif %}
                <div id="account-info" class="row justify-content-left m-3 p-3">
                    <div class="col-med-10">
                        <h3 class="text-primary">Your Account Info:</h3>
                    </div>
                    <div class="col-sm-5 container text-right">
                        <a href="{% url 'parkingapp:update-account' %}"><button type="button" class="btn btn-primary">Edit Info</button></a>
                    </div>
                </div>
                <div class="row m-1 p-1">
                    <ul style="list-style-type: none;">
                        <li class="text-primary">First Name: {{user.first_name}}</li>
                        <li class="text-primary">Last Name: {{user.last_name}}</li>
                        <li class="text-primary">Username: {{user.username}}</li>
                        <li class="text-primary">Email: {{user.email}}</li>
                    </ul>
                </div>
            </div>
            <div class="container rounded bg-light">
                <div id="account-balance" class="row justify-content-left m-3 p-3">
                    <div class="col-med-10">
                         <h3 class="text-primary">Account Balance: ${{user.profile.balance}}</h3>
                    </div>
                    <div class="col-sm-5 container text-right">
                        <a href="{% url 'parkingapp:transfer-funds' %}"><button type="button" class="btn btn-primary">Transfer Funds</button></a>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar fixed-bottom navbar-dark bg-primary" role="navigation">
            <div> <!-- Functionality for Lot Owners, Attendants, Supervisors -->
                <span>
                    {% if user.parkinglot_set.all|length > 0 %}
                    <a href="{% url 'parkingapp:lot-attendant-home' %}"><button type="button" class="btn btn-light">Lot Attendant Home</button></a>
                    {% endif %}
                    {% if user.profile.isSupervisor %}
                    <a href="{% url 'parkingapp:supervisor-home' %}"><button type="button" class="btn btn-light">Supervisor Home</button></a>
                    {% endif %}
                </span>
            </div>
        </nav>
    </div>
</body>
</html>

source/parkingapp/templates/parkingapp/manage_lot.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Manage Your Lot</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar fixed-top navbar-dark bg-primary" role="navigation">
        <h1 class="navbar-brand">BigBlueParkingGenie</h1>
        <div>
            <span> <!-- Directory -->
                <a href="{% url 'parkingapp:index' %}"><button type="button" class="btn btn-light">Home</button></a>
                <a href="{% url 'parkingapp:account-info' %}"><button type="button" class="btn btn-light">Account</button></a>
                <a href="{% url 'parkingapp:reserve-spot' %}"><button type="button" class="btn btn-light">Find Parking</button></a>
                <a href="{% url 'parkingapp:manage-lot' %}"><button type="button" class="btn btn-light">List Your Lot</button></a>
                <a href="{% url 'parkingapp:sign-out'%}"><button type="button" class="btn btn-danger">Log Out</button></a>
            </span>
        </div>
    </nav>

    <div class="container m-5 p-5"> <!-- view specific code here -->
        <div class="container m-auto">
            <h4 class="m-2 p-2 text-primary">Manage Your Lots</h4>
            <div class="container rounded bg-light row  m-3 p-3">
                <div class="container col-med-10 text-left">
                    {% if lot_list %}
                    {% for lot in lot_list %}

                    <div class="rounded bg-light row justify-content-left p-1 m-1">
                        <h5 class="pr-3">{{lot.nickname}}<span class="pr-3 font-weight-normal">- {{lot.address}}</span></h5>
                        <span>
                            <div class="btn-group dropright ">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Manage Availability</button>
                                <div class="dropdown-menu" >
                                {% if event_list %}

                                <form action="{% url 'parkingapp:list-lot' lot.id %}" method="post" class="px-4 py-3">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="event" class="text-primary">Choose Event:</label>
                                        <select id="event" name="selected-event" class="custom-select" onclick="stopPropagation(event)">
                                            {% for event in event_list %}
                                            <option type="text" value="{{event.id}}">{{event.name}} - {{event.date}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="distance-from-event" class="text-primary">Distance from Event in Miles:</label>
                                        <input type="number" id="distance-from-event" name="distance-from-event" class="form-control">
                                    </div>
                                    <div class="row justify-content-center">
                                        <input type="submit" value="Publish Availability" class="center btn btn-primary">
                                    </div>
                                </form>

                                {% endif %}

                            </div>
                            </div>
                        </span>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="container rounded bg-light row justify-content-center p-3 m-3 ">
                        <p class="text-danger font-weight-bold">No Lots Yet!</p>
                    </div>
                    {% endif %}
                </div>

                <div class="container col-med-2 text-right align-text-top">
                    <a href="{% url 'parkingapp:new-lot' %}"><button type="button" class="btn btn-primary">List A New Lot!</button></a>
                </div>
            </div>
        </div>

            <div class="container m-auto">
                <h4 class="m-2 p-2 text-primary">Lot Availability</h4>
                <div class="rounded bg-light row justify-content-center m-3 p-3">
                    {% if lot_event_data_list %}
                    {% for lot_event_data in lot_event_data_list %}
                    <div class="rounded bg-light row justify-content-center p-1 m-1">
                        <h5 class="pr-3">{{lot_event_data.parkingLot.nickname}}  |  {{lot_event_data.event.name}} <span class="text-muted"><small> on {{lot_event_data.event.date}}</small></span></h5>

                        <div class="pr-1">Motorcycle Spots left: {{lot_event_data.availableMotorcycleSpots}} |</div>

                        <div class="pl-1">Car spots left: {{lot_event_data.availableCarSpots}} |</div>
                        <div class="pl-1">Oversize spots left: {{lot_event_data.availableOversizeSpots}}</div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="container rounded bg-light row justify-content-center p-3 m-3 ">
                        <p class="text-danger font-weight-bold">No Listings Yet!</p>
                    </div>
                    {% endif %}
                </div>

            </div>




 <nav class="navbar fixed-bottom navbar-dark justicy-content-right bg-primary" role="navigation" style="z-index: -1;">
            <div> <!-- Functionality for Lot Owners, Attendants, Supervisors -->
                <span>
                    {% if user.parkinglot_set.all|length > 0 %}
                    <a href="{% url 'parkingapp:lot-attendant-home' %}"><button type="button" class="btn btn-light">Lot Attendant Home</button></a>
                    {% endif %}
                    {% if user.profile.isSupervisor %}
                    <a href="{% url 'parkingapp:supervisor-home' %}"><button type="button" class="btn btn-light">Supervisor Home</button></a>
                    {% endif %}
                </span>
            </div>
    </nav>



    </div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'parkingapp/script.js' %}"></script>
</body>
</html>

source/parkingapp/templates/parkingapp/reserve_spot.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Reserve A Spot!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar fixed-top navbar-dark bg-primary" role="navigation">
        <h1 class="navbar-brand">BigBlueParkingGenie</h1>
            <div>
                <span> <!-- Directory -->
                    <a href="{% url 'parkingapp:index' %}"><button type="button" class="btn btn-light">Home</button></a>
                    <a href="{% url 'parkingapp:account-info' %}"><button type="button" class="btn btn-light">Account</button></a>
                    <a href="{% url 'parkingapp:reserve-spot' %}"><button type="button" class="btn btn-light active">Find Parking</button></a>
                    <a href="{% url 'parkingapp:manage-lot' %}"><button type="button" class="btn btn-light">List Your Lot</button></a>
                    <a href="{% url 'parkingapp:sign-out'%}"><button type="button" class="btn btn-danger">Log Out</button></a>
                </span>
            </div>
    </nav>
    <div class="container m-5 p-5"> <!-- view specific code here -->
        <div class="container m-auto">
            <h4 class="m-2 p-2 text-primary">Reserve Parking Spot</h4>
            <div class="rounded bg-light row justify-content-center p-3">
                <form action="" method="post">
                    {% csrf_token %}
                    <label for="event" class="text-primary">Choose Event:</label>
                    <select id="event" name="selected-event" class="form-control">
                        {% for event in event_list %}
                        <option type="text" value={{event.id}} {% if selected_event_id == event.id %}selected{% endif %}>{{event.name}} - {{event.date}}</option>
                        {% endfor %}
                    </select><br>
                    <label for="spot-type" class="text-primary">Choose Spot Type:</label>
                    <select id="spot-type" name="spot-type" class="form-control">
                        <option value="1" {% if spot_type == "1" %}selected{% endif %}>Motorcycle</option>
                        <option value="2" {% if spot_type == "2" %}selected{% endif %}>Car</option>
                        <option value="3" {% if spot_type == "3" %}selected{% endif %}>Bus or RV</option>
                    </select><br>
                    <div class="row justify-content-center">
                        <input type="submit" value="Submit" class="center btn btn-primary"><br>
                    </div>
                </form>
            </div>
            {% if parking_list %}
            <h4 class="m-2 p-2 text-primary">Available Spots</h4>
            <div class="container rounded bg-light">
                {% for lot in parking_list %}
                <div class="rounded row justify-content-center p-3">
                    <span>|| Distance from event: {{lot.distanceFromEvent}} |</span>

                    {% if spot_type == "1" %}
                        <span class="pr-1">| Cost: ${{lot.parkingLot.motorcycleSpotPrice}} ||</span>
                    {% elif spot_type == "2" %}
                        <span class="pr-1">| Cost: ${{lot.parkingLot.carSpotPrice}} ||</span>
                    {% else %}
                        <span class="pr-1">| Cost: ${{lot.parkingLot.oversizeSpotPrice}} ||</span>
                    {% endif %}

                    {% if spot_type == "1" and user.profile.balance > lot.parkingLot.motorcycleSpotPrice or spot_type == "2" and user.profile.balance > lot.parkingLot.carSpotPrice or spot_type == "3" and user.profile.balance > lot.parkingLot.oversizeSpotPrice %}
                    <form action="{% url 'parkingapp:make-reservation' lot.id selected_event_id spot_type %}">
                        {% csrf_token %}
                        <input type="submit" value="Rent" class="center btn btn-primary">
                    </form>
                    {% else %}
                        <span style="color:red;">Insufficient Funds to Rent. Please update account balance in the Account tab.</span>
                    {% endif %}

                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
    <nav class="navbar fixed-bottom navbar-dark bg-primary" role="navigation">
        <div> <!-- Functionality for Lot Owners, Attendants, Supervisors -->
            <span>
                {% if user.parkinglot_set.all|length > 0 %}
                <a href="{% url 'parkingapp:lot-attendant-home' %}"><button type="button" class="btn btn-light">Lot Attendant Home</button></a>
                {% endif %}
                {% if user.profile.isSupervisor %}
                <a href="{% url 'parkingapp:supervisor-home' %}"><button type="button" class="btn btn-light">Supervisor Home</button></a>
                {% endif %}
            </span>
        </div>
    </nav>
</body>
</html>